
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "chefed-vvm" do |machine|
  end

 
 config.vm.provision :chef_solo do |chef|
 chef.arguments = '--chef-license accept'
    chef.cookbooks_path = "recipes/cookbooks"
   
   chef.add_recipe "nginx"
    chef.add_recipe "java"
    chef.add_recipe "tomcat"
    chef.add_recipe "mysql"

   end

  config.vm.network "forwarded_port", guest: 22,   host: 22022
  config.vm.network "forwarded_port", guest: 80,   host: 22080
  config.vm.network "forwarded_port", guest: 443,  host: 22443
  config.vm.network "forwarded_port", guest: 3306, host: 22306
end


